export const categories = [
    'Nhạc Trẻ', 'Trữ Tình',
    'Remix Việt', 'Pop',
    'Electronica/Dance',
    'Tiền Chiến',
    'Nhạc Trịnh',
    'Thiếu Nhi',
    'Cách Mạng',
    'Rap Việt',
    'Rock Việt',
    'Indie Việt',
    'Acoustic',
    'Soundtrack',
    'Rock',
    'R&B/Hip Hop/Rap',
    'Country',
    'Blues/Jazz',
    'Latin',
    'Indie',
    'Âu Mỹ Khác',
    'Nhạc Hàn',
    'Nhạc Hoa',
    'Nhạc Nhật',
    'Nhạc Thái',
    'Nhạc Pháp',
    'Nhạc Hoa Lời Việt',
    'Nhạc Sàn',
    'Nhạc Chúa',
    'Nhạc Phật',
    'Nhạc Ấn Độ',
    'Nhạc Vàng',
    'Bolero',
    'Hải Ngoại',
    'Audiophile',
    'Pop Ballad',
    'Cải Lương',
    'Opera',
    'Hợp Xướng - Chorus',
    'Vocaloid',
    'Utaite',
    'Không Lời',
    'Hòa Tấu',
    'Piano',
    'Guitar',
    'Saxophone',
    'Cello',
    'Violin',
    'Giao Hưởng - Classical',
    'Nhạc Cụ Dân Gian',
]

export const mood = [
    'Buồn', 'Cô Đơn',
    'FA', 'Nhớ Nhung',
    'Thất Tình',
    'Hưng Phấn',
    'Vui Vẻ',
    'Hy Vọng',
    'Quyết Tâm',
    'Ngọt Ngào',
    'Thư Giãn',
]

export const scene = [
    'Cafe', 'Du Lịch',
    'Buổi Sáng', 'Buổi Tối',
    'Buổi Trưa',
    'Lãng Mạn',
    'Lái Xe',
    'Làm Bài',
    'Làm Việc',
    'Aerobic',
    'Party',
    'Chơi Game',
    'Mua Sắm - Shopping',
    'Miền Bắc',
    'Mùa Xuân',
    'Tắm - Bơi Lội',
    'Đi Dạo - Chạy Bộ',
    'Bar - Club',
    'Giảm Stress',
    'Miền Nam',
    'Mùa Hạ',
    'Trước Khi Ngủ',
    'Tập Gym',
    'Phòng Trà',
    'Hẹn Hò',
    'Rạp Chiếu Phim',
    'Miền Trung',
    'Mùa Thu',
    'Thiền',
    'Thể Thao',
    'Họp Mặt',
    'Sân Trường',
    'Mưa',
    'Mùa Đông',
    'Yên Tĩnh',
    'Spa Yoga',
    'Đám Cưới',
    'Làm Việc Nhà',
    'Sinh Nhật',
    'Nắng',
    'Xế Chiều',
]

export const topic = [
    'Bất Hủ', 'Chill Out',
    'Nhạc Hot Tháng', 'Giải Thưởng Âm Nhạc',
    'Khiêu Vũ',
    'Cover',
    'Mashup',
    'Song Ca',
    'Top 100',
    'Band',
    'Baroque',
    'Cho Những Chuyến Đi',
    'Giáng Sinh',
    'Tết',
    'Weekend',
    'Cha',
    'Mẹ',
    'Bé',
    'Gia Đình',
    'Con Gái',
    'Con Trai',
    'Tình Bạn',
    'Tình Yêu',
    'Thầy Cô',
    'Epic Music',
    'Hoạt Hình',
    'Đoàn - Đảng',
    'Quê Hương',
]